// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_vCcpwjni5OzirP_Sk2LQJtS0ZO3rJwY',
    appId: '1:1010061060806:web:5e9fdd20480725212085c7',
    messagingSenderId: '1010061060806',
    projectId: 'recipe-app-61b57',
    authDomain: 'recipe-app-61b57.firebaseapp.com',
    storageBucket: 'recipe-app-61b57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrgH0ANMwuEkDgszvtl9d33xkYjs0DI0',
    appId: '1:1010061060806:android:dd5a2e14a4a56ada2085c7',
    messagingSenderId: '1010061060806',
    projectId: 'recipe-app-61b57',
    storageBucket: 'recipe-app-61b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpEffmWs6M8iDR1L2b5e_WJcGmAiaedDM',
    appId: '1:1010061060806:ios:919203992ff569f62085c7',
    messagingSenderId: '1010061060806',
    projectId: 'recipe-app-61b57',
    storageBucket: 'recipe-app-61b57.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpEffmWs6M8iDR1L2b5e_WJcGmAiaedDM',
    appId: '1:1010061060806:ios:919203992ff569f62085c7',
    messagingSenderId: '1010061060806',
    projectId: 'recipe-app-61b57',
    storageBucket: 'recipe-app-61b57.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_vCcpwjni5OzirP_Sk2LQJtS0ZO3rJwY',
    appId: '1:1010061060806:web:94a0afb987419f1e2085c7',
    messagingSenderId: '1010061060806',
    projectId: 'recipe-app-61b57',
    authDomain: 'recipe-app-61b57.firebaseapp.com',
    storageBucket: 'recipe-app-61b57.firebasestorage.app',
  );
}
